name: Update M3U

on:
  schedule:
    - cron: "0 * * * *"  # every hour
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download latest M3U
        run: curl -L "http://fluxtv.pro/ZKq6ob9NfFkAXzT" -o channels/FluxTV.m3u

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add FluxTV.m3u
          git commit -m "Auto-update M3U" || echo "No changes"
          git push
